name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/setup-node@v1
      - name: install http
        run: |
          npm install -g http-server
      - name: start http
        run: |
          http-server
      - name: http
        run: | 
          docker build ./http -t Luchezar03/14:1.0.0
      - name: docker push
        run: | 
          docker push luchezar03/14:1.0.0
