name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: npm install -g http-server
      - run: http-server
      - name: http
        run: | 
          docker build ./http -t Luchezar03/14:1.0.0
